### ISSUE TITLE
Investigate how to better the search in the top navigation

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-design-system#1025]
## Summary

Currently the search stops at page titles, but it would be good if it searched for:

- Words in sentences within pages
- Sub headings within pages 
- With components, search for similar names e.g. synonyms - find dialog if you typed in modal

It should highlight the letters that match the search term as you type.

## 💬 Description

It potentially needs to be designed eventually, but this spike is to look into ways that we could do it without needing too much design input or build it ourselves. 

If you look at react.dev or storybook, they both use Algolia, but that stops being free after 10K requests. Might still be worth looking into, but there's probably alternatives as well.

Try to stay away from anything that would need funding.

## 💰 Use value

More people would use the search function.

**Comment by GCHQ-Developer-847** [comment]
Research written up on a page in the internal knowledge base.

I will be creating tickets off the back of this investigation.
