### ISSUE TITLE
List item in anchor navigation not highlighting correct section

### ISSUE THREAD

**Issue by gd2910** [mi6/ic-design-system#1037]
## Summary of the bug

When using the anchor navigation and the previous selected <li> is still visible the focus will move to the newly selected section but the section highlight will remain on the previous one. 

## 🪜 How to reproduce

Tell us the steps to reproduce the problem:

1. Go to page: ['Alert'](https://design.sis.gov.uk/components/alert)
2. Click on: 'content' and then 'related content'
3. See the error

## 📸 Screenshots or code

![image](https://github.com/mi6/ic-design-system/assets/122624946/4e4edc4e-5307-4291-9ca9-e307acfe4ad1)

**Comment by GCHQ-Developer-299** [comment]
This is technically intended behaviour, the Related Components section is not tall enough to trigger the Table of Contents highlighting it's header is all.
