### ISSUE TITLE
[ic-pagination]: remove carousel variant guidance

### ISSUE THREAD

**Issue by jd239** [mi6/ic-design-system#1060]
## What component is this related to?

ic-pagination carousel variant

## Why do we need it?

This ticket is to remove the carousel alert and guidance from the guidance tab for `ic-pagination`. The carousel variant has been de-prioritised and can be removed from the site.  

## Related open issues

[Link to other GitHub issues]

**Comment by MI6-255** [comment]
Design to provide images
