### ISSUE TITLE
Update any reference of ic-card to ic-card-vertical

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-design-system#1080]
## What component is this related to?

Card

## Why do we need it?

On the V3 branch, ic-card is being renamed to ic-card-vertical. Our V3 site needs to reflect these changes.

Update code examples, any references in the guidance and anywhere we use cards on the site.

A suggestion was also made to update the names in the side nav to Card (Horizontal) and Card (Vertical) to help aid recognition.

## Related open issues

https://github.com/mi6/ic-ui-kit/issues/2216

**Comment by GCHQ-Developer-299** [comment]
This has been done as part of v3 guidance site changes :)
