### ISSUE TITLE
Update guidance site for changes to component sizing from `default` to `medium`

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-design-system#1090]
## Summary

Once changes for  https://github.com/mi6/ic-ui-kit/issues/2072 are complete, the site should be reviewed to ensure the examples use `medium` instead of `default`

Following components have had size 'default' updated to 'medium':  
Accordion
Badge
Button
Checkbox
Chip
Date picker
Empty state
Loading indicator
Page header
Radio button
Search bar
Status tag
Switch
Text field
Top navigation

**Comment by MI6-255** [comment]
Blocked by releasing v3
