### ISSUE TITLE
Explore allowing synonym searching on the website

### ISSUE THREAD

**Issue by GCHQ-Developer-847** [mi6/ic-design-system#1095]
## Summary
Explore whether it's possible to allow searching for synonyms on the ICDS website, and if so, implement it.

This ticket is has come out of the search investigation: #1025.

## 💬 Description
Currently, the website only allows exact search term matches. The issue with this is that users may sometimes have different names for components, e.g. "modal" instead of "dialog", so searching for that would not return any results.

This ticket is to investigate whether it's possible to improve the search functionality to make it return results which contain synonyms of the search term.

While researching for #1025, there was no evidence of FlexSearch having this option built-in so this ticket would involve exploring whether there are perhaps any separate libraries we could add which would work.

## 💰 Use value
This would help users find the information they are looking for more easily. It would particularly help those who are new to the ICDS and aren't familiar with certain component names. 

But it isn't just component names - there are probably a lot of words used throughout the ICDS website which have synonyms some people might be more used to.

## 📝 Acceptance Criteria
_Given_ that I am using the search bar / functionality on the website
_When_  I search for a particular term
_Then_ I see results which contain synonyms for that term (if there are any).

## Additional info
I am not completely sure if the correct term is "synonym searching" or "semantic searching"; the main thing is that the search should return results containing synonyms.

**Comment by GCHQ-Developer-847** [comment]
If there are no libraries or anything which would allow this, another solution would be to enhance the fields in the markdown files to perhaps include a "tags" field (or similar) and then include that field when searching (as Gatsby allows you to pass in the fields you want to search).

E.g. in the markdown files containing guidance about the dialog component, (alongside [`title`, `status`, etc.](https://github.com/mi6/ic-design-system/blob/02ed4ecda5900eed0fff6d44e4b671b60666d29d/src/content/structured/components/breadcrumbs/guidance.mdx?plain=1#L2-L16)) you could have:
`tags: "dialog"`

**Comment by MI6-255** [comment]
Spike and implementation in one
