### ISSUE TITLE
Add ICDS to the GitHub list of government design systems

### ISSUE THREAD

**Issue by GCHQ-Developer-112** [mi6/ic-design-system#11]
## What is the purpose of the work?
Add the ICDS to this [list of government design systems](https://github.com/ctdesign/gov-design-systems-list) to get increase exposure of the design system.

## Why do we need it?
This will help spread the word amongst the general public and other government departments.

**Comment by MI6-27** [comment]
Awaiting PR merge by the maintainer: https://github.com/ctdesign/gov-design-systems-list/pull/27

**Comment by GCHQ-Developer-112** [comment]
The PR above has been merged now 🎉🎉

The design system can now be seen on this [list of government design systems](https://github.com/ctdesign/gov-design-systems-list) 🥳
