### ISSUE TITLE
Website requires JavaScript and provides nothing without it

### ISSUE THREAD

**Issue by christopherJ-Defra** [mi6/ic-design-system#115]
## Summary of the bug
The design system's website requires JavaScript to load, without it I just get a blank page with no guidance, information, etc.

## 🪜 How to reproduce
Tell us the steps to reproduce the problem:
1. Go to page: `https://design.sis.gov.uk/` with JavaScript disabled (or in a browser without JavaScript)
2. See a completely blank page

## 🧐 Expected behaviour
The site appears to be mostly static content, it should work without requiring JavaScript (as should all components) based on the principle of [Progressive Enhancement](https://www.gov.uk/service-manual/technology/using-progressive-enhancement).

In the short term, at the least, the site should alert the user that JavaScript is required to view the site, for example using [`<noscript>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript) tags to provide an informative message (you can use CSS without JS to maintain the design system feel.)

## 🖥 Desktop
 - OS: Windows
 - Browser: Chrome
 - Version: 107

**Comment by MI6-255** [comment]
Thanks for your contribution, we're going to look into this within this sprint. We're aware there may be some accessibility requirements related to this too, so factoring this into the work. Feel free to keep an eye on this issue and we'll try update you if there is anything relevant throughout.

**Comment by MI6-255** [comment]
As an update, we initially added the message to enable JavaScript and have since put up a further change to render the majority of our website with JavaScript disabled, which will be merged shortly.

**Comment by ad9242** [comment]
reopened until website update is deployed

**Comment by ad9242** [comment]
Closing as updated site now deployed.
