### ISSUE TITLE
Implement all v3 changes onto v3 branch

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-design-system#1162]
## Summary

Implement all v3 changes onto v3 branch

## 💬 Description

All of the changes that have been implemented in the last couple of months on the v3 branch of the design system components, are yet to be implemented on the website. Each change needs adding so the website is working and showing all breaking changes.

Going forward, all changes need to be implemented on the website as part of the ticket.

## 💰 Use value

So they v3 version of the site in functional, ready for release.

**Comment by MI6-255** [comment]
Code examples needed

**Comment by ad9242** [comment]
the site should now be functional on the v3 branch, but code stackblitz examples need checking and\or updating to use v3 components
