### ISSUE TITLE
Website goes blank when clicking React button

### ISSUE THREAD

**Issue by nmcc1212** [mi6/ic-design-system#1173]
## Summary of the bug

When clicking "React" button in top navigation component example for "With React Router (using slots)", the whole page goes blank

## 🪜 How to reproduce

Tell us the steps to reproduce the problem:

1. Go to page: https://design.sis.gov.uk/components/top-navigation/code
2. Scroll down to "With React Router (using slots)" under "Variants"
3. Click on: React (button shown in red below)
<img width="859" alt="Screenshot 2024-10-17 at 5 24 00 pm" src="https://github.com/user-attachments/assets/fb03b0b1-5af5-4dfb-b4e8-4f6875e7b87b">
4. Whole page goes blank

## 📸 Screenshots or code

![output](https://github.com/user-attachments/assets/e588c24a-05e8-465d-ad16-b5e2f073223d)

Chrome console
<img width="695" alt="image" src="https://github.com/user-attachments/assets/2871381d-e3d1-4929-8713-3053d7efb317">

## 🖥 📱 Device

- Type: Desktop
- Device: MacBook 
- OS version: macOS 15
- Browser version: Tested on both Chrome (v129.0.6668.91) and Firefox (v131.0.3)

## 🧐 Expected behaviour

For the page not to have gone blank

## 📝 Acceptance Criteria

If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.

_Given_
_When_  
_Then_

## Additional info

Edit: This issue also occurs with the "Conditional tabs" variant demo

**Comment by MI6-255** [comment]
Any examples that only have the React option have this error
