### ISSUE TITLE
For each orgs icon in the footer, each footerLink there is a "listitem" and the parent element (the logo-wrapper) doesn't have role "list"

### ISSUE THREAD

**Issue by mi6-378** [mi6/ic-design-system#1174]
## Summary of the bug

After exploring the ICDS page accessibility, there appears to be an issue regarding the icons in the footer.

## 🪜 How to reproduce

Using the 'accessibility insights for web' chrome extension and testing the tabular format of any other the pages returns an issue regarding aria labels.

This is also visible in the automated checks part of this extension.

The process to fix is stated as: 'Required ARIA parent role not present: list'.

## 📸 Screenshots or code

<img width="1046" alt="Screenshot 2024-10-21 at 11 57 16" src="https://github.com/user-attachments/assets/4c95f48e-3622-4a2c-a1c0-e7ad641e92dc">

Automated checks: step 1 of 3

<img width="1162" alt="Screenshot 2024-10-21 at 11 57 59" src="https://github.com/user-attachments/assets/c5fa57ba-381d-412e-803b-07487b822cd1">

What the errors look like on this page

<img width="1429" alt="Screenshot 2024-10-21 at 11 32 53" src="https://github.com/user-attachments/assets/67741beb-3696-4a3d-87cd-998cfae25521">

Section 2 of 3 with tabular perspective

## 🧐 Expected behaviour

I expected there to be no issue regarding these and the tabbing to return no errors.

**Comment by GCHQ-Developer-299** [comment]
Followup task: https://github.com/mi6/ic-design-system/issues/1178
