### ISSUE TITLE
[ic-select-with-multi] Code example mistake

### ISSUE THREAD

**Issue by gd2910** [mi6/ic-design-system#1198]
## Summary of the bug

The top code demo for IcSelectWithMulti - Javascript doesn't contain an `options` array which breaks the example
Copy the options from examples below to fix the issue

## 📸 Screenshots or code

[Link to code example](https://design.sis.gov.uk/components/multi-select/code#component-demo)

**Comment by otutukingsley** [comment]
@gd2910 can you assign this issue to me? I would like to work on it.

**Comment by GCHQ-Developer-112** [comment]
Done @otutukingsley 👍

**Comment by otutukingsley** [comment]
@gd2910 @GCHQ-Developer-112 which line am I adding the options array to? I assume we are to make this change in the `code.mdx` file which is in the `src/content/structured/components/multi-select` directory.

**Comment by gd2910** [comment]
Hi @otutukingsley , you're adding the options array to line #108, above the return statement.

**Comment by otutukingsley** [comment]
@gd2910 I just created the PR for this issue, can you take a look when you have the time? Thank you!

**Comment by otutukingsley** [comment]
@gd2910 I just created a new PR for this issue, can you take a look when you have the time? Thank you!
