### ISSUE TITLE
Dark mode enable mechanism

### ISSUE THREAD

**Issue by GCHQ-Developer-094** [mi6/ic-design-system#1216]
## Summary 
In parallel with our dark mode offering, we want a means in order to both enable and disable (on and off) the implementation of said dark mode.

## 💬 Description 

It is assumed the use of a switch or toggle component will be utilised to achieve this. However, research should be conducted and various options presented.

## Outputs
- Conduct desk research
- Experiment with existing components but also don't be afraid to create something bespoke
- Several options to present back to team
- Think about how we will want to get feedback from the community before refining designs

## 💰 User value 
Easy out of the box means for customers to apply to products, ensuring seamless experience for the end user.

## Acceptance Criteria 
![Image](https://github.com/user-attachments/assets/2db916a5-e415-4b0b-9385-8f66ce34fc90)

**Comment by ad9242** [comment]
initial work done in #1222 

still to do:
- storing the setting
- detecting os\browser settings for default
- full dark mode of site
