### ISSUE TITLE
Website: Reduce weight of date in edit link at bottom of all pages

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-design-system#140]
## Summary of the bug
Date is currently bold and can be reduced to regular in weight. 

## 📸 Screenshots or code
<img width="392" alt="Screenshot 2022-12-14 at 13 24 56" src="https://user-images.githubusercontent.com/111882114/207607108-dddbbc49-b51f-4cc3-a474-fa7457843be5.png">

**Comment by ASM995** [comment]
Work complete
