### ISSUE TITLE
Website: padding for mobile version of status tag on website

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-design-system#142]
## Summary of the bug
The status tag has no space between the heading and the tag itself, causing it to look squashed up on the page

## 🧐 Expected behaviour
Status tags require padding in between heading and tag.

## 📸 Screenshots or code
![Screenshot 2022-12-14 at 13 59 54](https://user-images.githubusercontent.com/111882114/207614643-7f0e16a7-4715-4f31-8d66-0bd7092283a9.png)

## 📱 Mobile
 - Browser: safari

**Comment by ASM995** [comment]
This bug has been rectified in other development work.
