### ISSUE TITLE
Write section container guidance

### ISSUE THREAD

**Issue by GCHQ-Developer-741** [mi6/ic-design-system#160]
## What is the purpose of the work?

Guidance and code example of ic-section-container needs to be added.

Need design consultation on what should be written and what examples should be included

## Why do we need it?

So that users understand how to utilise this component correctly

**Comment by DBD324** [comment]
Written updates section container guidance. It can be found in the internal file share under 'Design work/Guidance/Section Container/..'. Images can be exported from Figma guidance site assets file.
