### ISSUE TITLE
Page header not sticky to top of page

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-design-system#168]
## Summary of the bug

Update guidance site to add sticky page header. 

## 🧐 Expected behaviour

1. Given that an asset page has long content and breakpoint is large or extra large, when the page scrolls, then the page header should stick to the top of the page. 

2. Given that an asset page has long content and breakpoint is medium, small or extra small, when the page scrolls, then the page header should not stick to the top of the page. 

## Additional info

There is now a "stickyDesktopOnly" prop that allows the sticky property to only be applied to browser widths of 992px and above

**Comment by GCHQ-Developer-530** [comment]
Not as simple as just adding the stickyDesktopOnly prop as once this is added then the page content goes over the top of the page header when scrolling. 

![Image](https://user-images.githubusercontent.com/111882034/217770416-f5927b93-f99e-43ce-a573-4e5a9b978a22.png)

**Comment by jd239** [comment]
This issue will be covered in https://github.com/mi6/ic-ui-kit/issues/391

**Comment by GCHQ-Developer-465** [comment]
The rest of this ticket still needs to be covered as there are 2 problems. One of them will be fixed through the https://github.com/mi6/ic-ui-kit/issues/391#issue-1589357099 ticket. Thanks.

**Comment by ad9242** [comment]
Reopened as this change was backed out due to a problem where anchor nav disappears behind sticky page header.
