### ISSUE TITLE
Internal buttons in Search Bar component display issues

### ISSUE THREAD

**Issue by fbd399** [mi6/ic-design-system#17]
## Summary of the bug
The pressed (:active) state of the internal clear button on the search bar component renders as the focus state, rather than the designed pressed state of icon buttons.

## 🧐 Expected behaviour
Expected behaviour is to display the default pressed state for icon buttons.

## 🖥 Desktop
As seen on:
- OS: macOS
- Browser: Chrome Version 107.0.5304.87

## Screenshot

![Image](https://user-images.githubusercontent.com/110023487/200785478-72ca3906-d875-444b-a4ad-86690129e47c.png)

**Comment by GCHQ-Developer-847** [comment]
Spoke to @fbd399 and we have decided to close this ticket as the focus behaviour matches that of the other components (the focus state overrides other states). 

The issue of focus states appearing on click is something that will be explored in the near future.
