### ISSUE TITLE
Using "Scroll to top" button with the Anchor navigation causes the navigation to not recognise the anchor

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-design-system#172]
## Summary of the bug

Using "Scroll to top" button with the Anchor navigation causes the navigation to not recognise the anchor

## 🪜 How to reproduce

1. Go to a page such as https://design.sis.gov.uk/components/cards#
2. Scroll to the bottom
3. Click "Scroll to top"
4. Observe how Anchor navigation does not recognise the correct location until you scroll again

## 🧐 Expected behaviour

Expect it to recognise the location after pressing back to top

**Comment by ad9242** [comment]
think this is fixed

**Comment by MI6-255** [comment]
Fixed already
