### ISSUE TITLE
Tabs on component pages return the user to the top of the page

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-design-system#173]
## Summary of the bug

Tabs on component pages return the user to the top of the page

## 🪜 How to reproduce

1. Go to a component page such as: https://design.sis.gov.uk/components/breadcrumbs
2. Scroll down slightly
3. Click on a tab such as Guidance, Code or Accessibility
4. Notice how the page returns to the top between each tab

## 🧐 Expected behaviour

Expected to stay in the same screen position

## Additional info

Do we need to offer guidance on how others do this when they use Tabs if this isn't isolated to the microsite?

**Comment by ASM995** [comment]
Closing as work will be covered in a separate ticket.
