### ISSUE TITLE
Unable to enter a space into search on Top Navigation 

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-design-system#174]
## Summary of the bug

Unable to enter a space into search on Top Navigation 

## 🪜 How to reproduce

1. Go to the website https://design.sis.gov.uk/ 
2. Type "static chip" in search bar
3. Notice how there is no space between "static" and "chip"

## 🧐 Expected behaviour

A space to appear when pressed

**Comment by Project-4040** [comment]
Two presses on the space bar adds a space. However, a full stop (.) is also inserted at the end of the first word after a couple of presses of the space bar. This behaviour seems intermittent, though.
