### ISSUE TITLE
Add documentation of ic-menu component to site

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-design-system#177]
## What is the purpose of the work?
add documentation of ic-menu component into the Select and Search bar pages

## Why do we need it?
We document other dependencies, such as navigation items\buttons for top navigation and side navigation. We should document this one too

**Comment by c00kie123** [comment]
Hey I am interested in this!

**Comment by ad9242** [comment]
This needs adding to the ic-select & ic-search-bar docs:

<ComponentDetails component="ic-menu" />

**Comment by ad9242** [comment]
Closed without documenting as ic-menu is not used directly. It is only used internally used by ic-search-bar & ic-select
