### ISSUE TITLE
Iconography viewer

### ISSUE THREAD

**Issue by MI6-451** [mi6/ic-design-system#181]
## Summary

Investigate iconography viewer component

## 💬 Description

Investigate the custom 'viewer' component used on the Icon page of the styling section of the website to ensure that it matches the styling of the rest of the site.

## 💰 Use value

Ensure that where we use custom 'one-off' components they match the styling of the component library. Ensure styling is consistent across the website.

## Additional info

Tell us anything else useful to help us understand your suggestion.

**Comment by GCHQ-Developer-094** [comment]
Won't do for now
