### ISSUE TITLE
Toggle state for search button in App bar

### ISSUE THREAD

**Issue by GCHQ-Developer-741** [mi6/ic-design-system#183]
## Summary
Add some toggle state to the button that shows/hides the search bar in small/medium screen sizes on the guidance site.

## 💬 Description
Create toggle states for the search button within the small/medium layout for app bar. When the search bar is expanded the search button should indicate it is open, and when the search bar is closed the button should indicate it is closed. The button acts as a toggle for expanding and closing the search bar.

## 💰 Use value
Make it more obvious what the purpose of the button is and what state it is in

**Comment by GCHQ-Developer-094** [comment]
Won't do for now
