### ISSUE TITLE
Pop up search (on smaller devices) pushes other page content

### ISSUE THREAD

**Issue by GCHQ-Developer-741** [mi6/ic-design-system#184]
## Summary
When the search bar is opened on smaller devices, it pushes the rest of the page content down.

## 💬 Description
The pop up search (on smaller devices) pushes other page content. Think this is a failure & it should pop over. Needs investigation and design as to styling etc if it's a popover

## 💰 Use value
Prevents the screen content from moving too much.

**Comment by GCHQ-Developer-094** [comment]
Won't do for now
