### ISSUE TITLE
Search bar behaviour on smaller device/screen sizes

### ISSUE THREAD

**Issue by MI6-451** [mi6/ic-design-system#185]
## Summary
Investigate possible solutions to improve the behaviour of the search bar 'pop up' on smaller device/screen sizes.

## 💬 Description
Currently on smaller device/screen sizes the search bar is implemented as a 'pop up' which pushes other content on the page down when it is displayed. We are not sure if this is still the best approach and so should investigate possible implementations with the search bar as a 'popover' which would sit above other page content when it is displayed. Exact designs and behaviour to be determined.

## 💰 Use value
Reducing page/content movement would improve accessibility and overall user experience.

**Comment by MI6-255** [comment]
@DBD324 could we link this to the Sticky top navigation ticket

**Comment by GCHQ-Developer-094** [comment]
Won't do for now
