### ISSUE TITLE
Guidance for CSS tokens

### ISSUE THREAD

**Issue by MI6-451** [mi6/ic-design-system#187]
## Summary
Add guidance for using CSS tokens.

## 💬 Description
The UI kit offers developers CSS tokens which help to ensure application styles better match those used in the components. There should be guidance on the site to better explain the use of these tokens including listing the tokens as they would be used in code, potentially with examples. A component similar to the 'props table' used for components would be useful to show CSS tokens on relevant pages.

## 💰 Use value
Better documentation for the CSS tokens and their usage would improve developer experience when employing them.

**Comment by MI6-255** [comment]
Will review with our theming piece of work
