### ISSUE TITLE
Display issue with pressed (:active) state for non-visited white links

### ISSUE THREAD

**Issue by fbd399** [mi6/ic-design-system#19]
## Summary of the bug
The pressed (:active) state of the ‘Get started’ hyperlink on the homepage (and all other white links in the website) doesn’t render correctly. This is only the case when the link is not visited. For visited links, the issue doesn’t apply.

## 🧐 Expected behaviour
Currently it reverts to blue. Expected behaviour is to maintain the white colour.

## 🖥 Desktop
As seen on:
- OS: macOS
- Browser: Chrome Version 107.0.5304.87

## Screenshot

![Image](https://user-images.githubusercontent.com/110023487/200783004-83aab901-ec11-4230-9b8b-4646b34e3ce2.png)

**Comment by jd239** [comment]
I'm currently having this issue in FF
![image](https://user-images.githubusercontent.com/116016939/205940349-cd1760b7-0371-48d4-9d5a-55cf3fc2cdc4.png)
