### ISSUE TITLE
'Check and review' patterns

### ISSUE THREAD

**Issue by MI6-451** [mi6/ic-design-system#190]
## Summary
The guidance currently alludes to 'review' or 'check before you submit' pages. We should consider elaborating this guidance.

## 💬 Description
There are some good established patterns for 'check and review' pages in other Design Systems but we haven't considered the value, nor seen 'good examples' in the ICDS. 

## 💰 Use value
Examples of 'check and review' pages/interactions will allow developers to gain a better understanding of what their own implementations should achieve.

## Additional info
Consider the specific use case of ICDS applications, e.g. data heavy applications.

**Comment by GCHQ-Developer-094** [comment]
Won't do for now
