### ISSUE TITLE
Update guidance on stepper and include compact stepper examples

### ISSUE THREAD

**Issue by GCHQ-Developer-112** [mi6/ic-design-system#198]
## Summary

With the addition of the compact variant of the stepper, guidance on the stepper should be reviewed. Code examples for the compact variant should also be added. Existing code examples should be reviewed and changed as relevant.

## 💰 Use value

An update to the stepper guidance will help our users when using the stepper component and make the use case for it clear.

**Comment by GCHQ-Developer-112** [comment]
Code examples to add:

- [ ] With hidden step titles
- [ ] Compact
- [ ] Add alert to without step titles

**Comment by DBD324** [comment]
Remove alert without step titles, as this is bad practice and we do not want to encourage it even if it is technically possible. We will look to include a change in next major release that forces you to include step titles, even if not displayed.
