### ISSUE TITLE
Update guidance on chips and include chip code examples

### ISSUE THREAD

**Issue by GCHQ-Developer-112** [mi6/ic-design-system#199]
## Summary

With the addition of the new chips components, guidance on chips should be reviewed. Code examples for chips should also be added.

## 💰 Use value

An update to the chips guidance will help our users when using the chips component and make the use case for it clear.

## Additional info

This issue is currently on hold whilst chips goes through accessibility testing.

**Comment by DBD324** [comment]
This duplicates #211 . Closing this ticket as more information is housed in 211.
