### ISSUE TITLE
Document versioning approach

### ISSUE THREAD

**Issue by MI6-451** [mi6/ic-design-system#202]
Release end of sprint, but can easily change.

Follow SEMVER, but with that breaking changes extra

Need to be bringing it into sprint planning/PI planning our major breaking changes

Need to communicate the regular releases (e.g. say 12 months) and how frequent and give people notice (give people the next tag)

**Comment by jd239** [comment]
We have this page ( https://design.sis.gov.uk/get-started/releases-versions) which I'm assuming closes the ticket - unless there is more required?
