### ISSUE TITLE
Update chips guidance page to include newly released component

### ISSUE THREAD

**Issue by DBD324** [mi6/ic-design-system#211]
## What is the purpose of the work?
Chips is ready to release so the guidance page can be updated to display the new component. 
- Remove 'coming soon' alerts. 
- Update code page to include component demo, props tables, variants. 
- Update guidance imagery to use updated images. See Figma 'Design System Microsite Assets' file for latest imagery. 
- Add chips video animation. 

## Why do we need it?
Guidance should reflect that component is now available for use and should contain the component demos for live component.

**Comment by DBD324** [comment]
@fbd399 Please provide the chips updated imagery, video and guidance changes. Thanks

**Comment by DBD324** [comment]
Updated imagery and video content can be found in the Chips folder in the guidance section of the internal team share.

**Comment by GCHQ-Developer-530** [comment]
I'm not sure the imagery in this folder is correct as it includes the green bar and tick in the image, but that should be something we add using DoDontCaution
