### ISSUE TITLE
Styling of visited link in Firefox not accessible

### ISSUE THREAD

**Issue by MI6-94** [mi6/ic-design-system#219]
## Summary of the bug

The styling of the visited link on the homepage hero remains the default purple visited colour on dark background.

## 🪜 How to reproduce

Tell us the steps to reproduce the problem:

1. Go to page: homepage
3. Click on: 'Get started' in the hero.
4. Return to the homepage.
5. The 'Get started' link is purple and cannot be seen.

## 🧐 Expected behaviour

The link should remain white even after it has been visited.

## 📸 Screenshots or code

![image](https://user-images.githubusercontent.com/90764530/212633946-32d5e271-a894-438d-9020-57700c569c15.png)

## 🖥 Desktop

- Browser: Firefox

**Comment by ASM995** [comment]
Work has been complete.
