### ISSUE TITLE
Uploading a file component

### ISSUE THREAD

**Issue by MI6-94** [mi6/ic-design-system#223]
## Summary

Ability up upload a file file browse or drag and drop files to upload.

## 💰 User value

Would enable users to quickly upload files and is currently a pattern we do not have.

## 📚 User Stories

To be populated in the future.

## 📝 Acceptance Criteria

To be populated in the future.

- User should be able to drag and drop files to upload.
- Click a button to choose a file to upload.
- Once the user has uploaded a file it should be inside the drop zone.
- User can confirm upload or see success or upload.

## ✏ Designs

To be populated more in the future.

An example of how the component could behave.
![Screenshot 2021-12-06 at 09 53 06](https://user-images.githubusercontent.com/90764530/212718515-ff0ea9cd-9ec7-4bcb-8679-11ef72604b4b.png)

**Comment by GCHQ-Developer-530** [comment]
https://github.com/mi6/ic-ui-kit/issues/180

**Comment by MI6-94** [comment]
Duplicate ticket.
