### ISSUE TITLE
Flashing website and disappearing/changing components

### ISSUE THREAD

**Issue by fbd399** [mi6/ic-design-system#225]
## Summary of the bug

When loading, the website's pages seem to very briefly flash. By analysing a video recording of a page being loaded, it is clear that at first some elements render incorrectly, after which they disappear completely, and reappear rendered correctly. Need to investigate how to solve this.

## 🪜 How to reproduce

Tell us the steps to reproduce the problem:

1. Go to page: 'Homepage'
2. Click on: 'Read the story of our Design System.'
3. See the error

## 🧐 Expected behaviour

No flashing; components should load accurately the first time.

## 📸 Screenshots or code

![Bug](https://user-images.githubusercontent.com/117087335/212722118-63462a61-f492-4f82-ae72-95151f83b02f.jpg)

## 🖥 Desktop

- OS: macOS
- Browser: Safari

**Comment by GCHQ-Developer-847** [comment]
See [my comment on another FOUC-related ticket](https://github.com/mi6/ic-ui-kit/issues/1415#issuecomment-1997155336)
