### ISSUE TITLE
Popover/overflow menu component

### ISSUE THREAD

**Issue by MI6-94** [mi6/ic-design-system#226]
## Summary

This provides a method of offering additional links/actions when space is constrained. The component could be launched from a kebab menu and can have different types of options and section titling.

## 💰 User value

To help users have easy access to multiple quick actions in small spaces.

## 📚 User Stories

To be populated in the future.

## 📝 Acceptance Criteria

To be populated in the future.

## ✏ Designs

To be populated in the future.

**Comment by GCHQ-Developer-530** [comment]
https://github.com/mi6/ic-ui-kit/issues/258

**Comment by MI6-94** [comment]
Duplicate ticket.
