### ISSUE TITLE
Quick filter bar component/pattern

### ISSUE THREAD

**Issue by MI6-94** [mi6/ic-design-system#227]
## Summary

Simple bar of filters for quick access. (Needs research to decide if this belongs to search page pattern or data tables).

## 💰 User value

To be populated in the future.

## 📚 User Stories

To be populated in the future.

## 📝 Acceptance Criteria

To be populated in the future.

## ✏ Designs
Example of the filter bar.
![image (1)](https://user-images.githubusercontent.com/90764530/212724307-15206d36-5fc3-41cc-9e16-8a859eb9d341.png)

**Comment by GCHQ-Developer-530** [comment]
https://github.com/mi6/ic-ui-kit/issues/236

**Comment by MI6-94** [comment]
Duplicate ticket.
