### ISSUE TITLE
Add error state to stepper

### ISSUE THREAD

**Issue by MI6-94** [mi6/ic-design-system#229]
## Summary

Add error state to stepper to give visual cue when the user needs to return to a step.

## 💬 Description

The stepper should be able to display an error state, for example if there was missed information on that step.

## 💰 Use value

To be populated in the future.

Example of design:
![Screenshot 2023-01-16 at 16 35 11](https://user-images.githubusercontent.com/90764530/212727164-8b9a8fab-1c24-45ff-956f-bdc16582d0ab.png)

**Comment by MI6-255** [comment]
Won't do, due to a design decision that this would not follow our guidance on showing errors. We will look at displaying errors in other patterns in the future.
