### ISSUE TITLE
Explore contrast of disabled button text and background

### ISSUE THREAD

**Issue by MI6-94** [mi6/ic-design-system#230]
## Summary

Explore the contrast of labels on disabled buttons.
Note: Disabled buttons do not need to pass normal accessibility guidelines around colour contrast, however we want to try to make disabled button labels still readable. 

## 💬 Description

Research and make the changes to improve the readability.

## 💰 Use value

So that all users can quickly identify disabled buttons.

## Additional info

- Changing colours to up contrast without making button seem 'enabled'.
- Introduce non-colour element to indicate disabled state (dashed line similar to text fields)

**Comment by GCHQ-Developer-530** [comment]
https://github.com/mi6/ic-ui-kit/issues/275

**Comment by MI6-94** [comment]
Duplicate ticket.
