### ISSUE TITLE
Guidance for using the ICDS Search Bar where options are fetched on each keyboard input

### ISSUE THREAD

**Issue by MI6-651** [mi6/ic-design-system#231]
## Summary
Add guidance for using the ICDS Search Bar where 'options' are obtained asynchronously and change on each keyboard input.

## 💬 Description
The website currently does not have any guidance for using the ICDS Search Bar where suggestions are retrieved asynchronously, e.g. from an API or database using the search query. Guidance should be added for this use case.

## 💰 Use value
A common use case for search bar components is querying data from a server or database, rather than hard coded in a UI. Guidance for using the ICDS Search Bar like this will help developers implement this functionality and provide a best practice of how to do so.

**Comment by jd239** [comment]
This ticket is blocked until https://github.com/mi6/ic-ui-kit/issues/297 is completed

**Comment by ad9242** [comment]
Guidance site has been updated with a custom filtering example on search bar code tab
