### ISSUE TITLE
Small typos in code examples

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-design-system#252]
## Summary

There are small typos in some of the code examples on the guidance site.

## 💬 Description

1. In the react example of breadcrumbs, the second breadcrumb href has an extra space (see screenshot 1)
2. Skeleton contains height="20" but height doesn't exist (see screenshot 2)
`<IcSkeleton variant="circle" height="20" />`
3. Seems like it could just be a typescript issue, but textfield example comes with `maxLength="25"` but a string isn't assignable to a number so it would only accept `maxLength={25}` (see screenshot 3)
4. The Select react example has `const [value, setValue] = useState(null);` however in typescript projects where `<string>` is needed, null causes errors. Should look more like this for typescript projects: `const [value, setValue] = useState<string>("");`

## 💰 Use value

Users should be able to copy and paste code examples without getting errors.

## Additional info
1. <img width="532" alt="Screenshot 2023-01-30 at 09 17 25" src="https://user-images.githubusercontent.com/111882034/215436388-b1810c9f-0e46-4b64-9d0f-9490d7ca2be6.png">
2. <img width="599" alt="Screenshot 2023-01-30 at 09 19 41" src="https://user-images.githubusercontent.com/111882034/215436736-13f4f176-aec9-42cc-be81-3fa96207d4d8.png">
3. <img width="609" alt="Screenshot 2023-01-30 at 09 21 46" src="https://user-images.githubusercontent.com/111882034/215437233-8def5004-deaa-403d-9cb6-234b8d027cdf.png">

**Comment by GCHQ-Developer-112** [comment]
In relation to point 2, the prop `rows` on the react component `IcTextField` is a number type. The react examples with the prop `rows` should be in brackets instead of speech marks, e.g. {6}
<img width="591" alt="Screenshot 2023-01-30 at 12 45 15" src="https://user-images.githubusercontent.com/113986285/215860640-909cbb91-a7a6-4784-9980-062989820f6a.png">

**Comment by Faizan-omer** [comment]
Hi, kindly assign this to me
