### ISSUE TITLE
Page contents active/scroll not behaving correctly

### ISSUE THREAD

**Issue by MI6-94** [mi6/ic-design-system#298]
## Summary of the bug

The page contents 'active' doesn't align with where the user is on the screen. On certain pages the page is too short for the page contents to scroll through all the sections.

## 🪜 How to reproduce

Tell us the steps to reproduce the problem:

For example head to https://design.sis.gov.uk/components/classification-banner/#content, click away from content then back to content and colour gets selected.

## 🧐 Expected behaviour

The page contents should scroll with where the user is on the page. When navigating sections to page content should keep up and the 'active' page should be accurate.

## 📸 Screenshots or code

![image (2)](https://user-images.githubusercontent.com/90764530/219054479-64a6597f-4463-4aca-9b76-7ad69fec2145.png)

**Comment by DBD324** [comment]
Will be delivered by https://github.com/mi6/ic-ui-kit/issues/752
