### ISSUE TITLE
Off-screen text pattern for Assistive Tech/screen-reader interactions

### ISSUE THREAD

**Issue by MI6-27** [mi6/ic-design-system#30]
## Summary
We think it would be great to have a documented pattern how the ICDS (and consumers) can deal with 'off-screen' screen-reader/assistive tech text.

## 💰 User value
This will allow the ICDS and implementing products to create consistent experiences for those users who find such offscreen/hint text valuable.

## 📝 Acceptance Criteria 
As this is a pattern, this work would involve investigation of 'best practice', some user research and testing. We'd expect an actual documented pattern but can't presume what that'll be yet 😅.

Contribution criteria for patterns would apply.

## ✏ Designs
N/A. 

## 🧾 Guidance
N/A.

**Comment by GCHQ-Developer-094** [comment]
Won't do for now
