### ISSUE TITLE
Add more details on SlottedSVG usage with MUI Icons

### ISSUE THREAD

**Issue by jd239** [mi6/ic-design-system#301]
## Summary

After experimenting with MUI Icons and SlottedSVG, it has become apparent that to use MUI Icon, a different package is required to what is suggested on the MUI website. This should be documented in the guidance site. 

## 💬 Description

A utility component called SlottedSVG is being provided from `@ukic/react` to prevent any TS errors regarding the slot attribute and SVG elements. SlottedSVG provides the parent SVG tag and allows the consumer to provide the path via a prop or as its children. However, if importing an icon from MUI, the MUI icon also contains the SVG tag causing rendering issues. This ticket is to provide guidance to using the SlottedSVG with `@mdi/js` instead. 

## 💰 Use value

Help consumers import SVGs based on the Material Design iconset within their applications using the `SlottedSVG`.

## Additional info

Add an example on the Side Navigation code example using MUI Icons as well.

**Comment by GCHQ-Developer-112** [comment]
Example of [how to use an icon from the `@mdi/js` package](https://github.com/mi6/ic-ui-kit/pull/379#discussion_r1108541185)
