### ISSUE TITLE
Spelling mistake in toast example image

### ISSUE THREAD

**Issue by MI6-94** [mi6/ic-design-system#302]
## Summary of the bug

Spelling mistake in the image of toast example.

## 🪜 How to reproduce

Tell us the steps to reproduce the problem:

1. Go to page: Toast component.
2. Look at: Multiple images (first 3 on guidance page). - "a fascinating topic, I woul love to hear more."

## 🧐 Expected behaviour

It should be 'would'.

## 📸 Screenshots or code
![Screenshot 2023-02-17 at 13 38 34](https://user-images.githubusercontent.com/90764530/219667928-ed75c817-4d51-4aff-a842-41c55a85d384.png)

**Comment by ad9242** [comment]
fixed in latest release
