### ISSUE TITLE
Update SlottedSVG code snippets in all relevant components

### ISSUE THREAD

**Issue by jd239** [mi6/ic-design-system#320]
## Summary

Update the `<SlottedSVG ...>` examples in all relevant code snippets.

## 💬 Description

At the moment, all our code snippets which contain `<SlottedSVG ...>` appear truncated to reduce the amount of code in the `ComponentPreview` component. Since we have a Copy Code button, it will be more useful to the developer if they were able to copy and paste the code straight into their application without having to make additional updates due to our __incomplete__ code examples. 

## 💰 Use value

It will be more useful to the developer if they were able to copy and paste the code into their application without having to make additional updates due to our __incomplete__ code examples. 

## Additional info

How to use the SlottedSVG can be found here: https://design.sis.gov.uk/get-started/install-components/react/#working-with-slotted-svgs

**Comment by MI6-255** [comment]
[#321](https://github.com/mi6/ic-design-system/issues/321)

**Comment by ad9242** [comment]
fixed by https://github.com/mi6/ic-design-system/pull/379
