### ISSUE TITLE
Add imports to component pages

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-design-system#321]
## Summary

At the moment, we allow users to copy code from our code examples on the guidance site, but it can then be time consuming for them to go through and ensure they've added the correct imports for each of the components copied in. It'd be good if we could provide those import statements for them for each variant.

## 💬 Description

At the top of each code page we could have the main import e.g for side navigation we'd have 
`import { IcSideNavigation } from "@ukic/react";`

Then for each variant, we'd have the extra relevant imports e.g 
`import { SlottedSVG, IcNavigationItem, IcNavigationGroup } from "@ukic/react";`

Might need design input on how this would actually look and sit on the page, e.g if it wants to be under the title of each variant like suggested above, or whether we want another section on each code page like we have "Side navigation details" we could also have "Side navigation imports". Or add the imports to the code examples somehow?

Also need to consider how we display both web component and react imports.

## 💰 Use value

Smoother for the developer as they can copy imports easily.

**Comment by MI6-255** [comment]
Design input on "hide full source", "show full source" for showing the imports. Links to a bigger ticket on code snippet on using code pens etc

**Comment by MI6-255** [comment]
Requested by a customer yesterday

**Comment by GCHQ-Developer-112** [comment]
This will be solved by #751
