### ISSUE TITLE
Back to top is covering the date/content when on mobile viewport

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-design-system#336]
## Summary of the bug

The back to top is covering content such as the 'last reviewed date'. This would need to take looking into from a design perspective first. 

## 🪜 How to reproduce

1. Minimise the viewport so that it is on mobile view / test the site on mobile. 
2. Go to the [components page  ](https://design.sis.gov.uk/components)
3. Scroll to the bottom 
4. See the error

## 🧐 Expected behaviour

The back to top should not be covering the content. 

## 📸 Screenshots or code
<img width="214" alt="Screenshot 2023-03-09 at 14 32 44" src="https://user-images.githubusercontent.com/111882114/224056880-a7a8efc0-6a83-4480-93ce-4220cb02af60.png">

## Additional info

Designers may want to look into this first to discuss the positioning of 'back-to-top'

**Comment by GCHQ-Developer-094** [comment]
Partially resolved by ticket #960 - implement icon only version?

**Comment by GCHQ-Developer-094** [comment]
May coincide with work on ticket #2026

**Comment by GCHQ-Developer-465** [comment]
![Image](https://github.com/user-attachments/assets/5ea8c2c8-a734-495f-8c9a-7431a3001a39)

Checked again and is still a problem.

**Comment by MI6-255** [comment]
Icon only variant may resolve this, which will not happen until v3

**Comment by ad9242** [comment]
covered by #959

**Comment by GCHQ-Developer-299** [comment]
Closing this because it will be fulfilled by 959
