### ISSUE TITLE
back-to-top not on landing page for site

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-design-system#338]
## Summary of the bug

The back-to-top component is not on landing page for site. For consistency the component should be displayed like it has been for the other pages. 

## 🪜 How to reproduce

Tell us the steps to reproduce the problem:

1. Go to https://design.sis.gov.uk/
2. Scroll to bottom then scroll back up 
3. See the error as no back-to-top appears like the other pages 

## 🧐 Expected behaviour

For the back-to-top to be displayed on the landing page. 
![Screenshot 2023-03-14 at 14 29 47](https://user-images.githubusercontent.com/111882114/225033636-9fd0f8c6-0422-45c7-ab64-2babb0504abe.png)

## 📸 Screenshots or code
![Screenshot 2023-03-14 at 14 29 35](https://user-images.githubusercontent.com/111882114/225033551-a42688d5-e685-487c-8c4d-f1261927a218.png)
![Screenshot 2023-03-14 at 14 29 40](https://user-images.githubusercontent.com/111882114/225033610-91024ab1-ef94-4c71-922d-bb9a68033d2a.png)

## Additional info

This may need to be discussed first with designers.

**Comment by GCHQ-Developer-530** [comment]
Completed: https://github.com/mi6/ic-design-system/pull/399
