### ISSUE TITLE
Review how we version our components etc

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-design-system#354]
## Summary

Review how we can version our components (with moving away from the beta wide branding)

## 💬 Description

The outcome of this should be a documented approach on when design/development agree a component matures through it's versions (alpha, beta etc), with additional work to retrospectively apply that approach to our current website

**Comment by jd239** [comment]
Links to https://github.com/mi6/ic-design-system/issues/361

**Comment by ASM995** [comment]
Closed as work complete in separate ticket.
