### ISSUE TITLE
Investigate automated Ticket management ('bots')

### ISSUE THREAD

**Issue by MI6-27** [mi6/ic-design-system#36]
Please can we investigate the use of automations and bots within the projects?

We could automate/improve things such as:
- Welcoming new users when they raise a ticket, and point to the contribution guidelines and Contributor's License Agreement (if it's not a PR - because they'd have signed it anyway).
- Automatically assigning tickets based on keywords to people, labels or milestones.
- Closing tickets that don't meet a template or certain standards.
- Closing old issues as 'stale' depending on some criteria.

**Comment by GCHQ-Developer-112** [comment]
We now have a GitHub action that welcomes new users on their first issue & PR. It points them to the contribution guidelines, code of conduct & CLA

**Comment by ASM995** [comment]
Automation work underway and documented in other tickets.
