### ISSUE TITLE
Website: Improve icon picker

### ISSUE THREAD

**Issue by MI6-27** [mi6/ic-design-system#38]
### ⭐️ Is your improvement suggestions related to a problem?
Investigate current iconography viewer components and ensure it matches styling of rest of site. 

This is the bespoke component used on the `Styles/Icons` page.

### 💬 Describe the improvement you would like
To make sure the design tokens and overall page/interaction fits the rest of the site.

**Comment by GCHQ-Developer-094** [comment]
Won't do for now
