### ISSUE TITLE
[ic-top-navigation]: Fly-out menu which appears on mobile cuts through component preview

### ISSUE THREAD

**Issue by jd239** [mi6/ic-design-system#389]
## Summary of the bug

Opening up the fly out menu from the mobile top navigation displays z-index issues with the component preview. This may be related to https://github.com/mi6/ic-design-system/pull/372. 

Edit: After further investigation, the z-index issue displays depending on which component preview the top navigation resides from. For example, (on the top navigation guidance page), clicking on the main top nav at the top of the site does not reproduce the error. Select the next one down, it fly out menu only cuts through the component preview below. Click the menu button in the last component example, the fly out menu is above both component previews.

## 🪜 How to reproduce

Tell us the steps to reproduce the problem:

1. Go to page: https://design.sis.gov.uk/components/top-nav
2. Click 'Menu' on the top navigation component (view in mobile / small viewport)

## 🧐 Expected behaviour

Fly out menu should be appearing above all content on the page (except classification banner)

## 📸 Screenshots or code
![Capture](https://user-images.githubusercontent.com/116016939/229153096-533b16f2-d60f-4b06-946c-03016eed893a.PNG)

## 🖥 Desktop

- OS: Windows
- Browser: Chrome
- Browser version: 111
- Website version: V2
  (As displayed on the site top navigation)

This issue can be recreated by reducing the viewport of the browser

## 📱 Mobile

- Device: Android
- OS: Android
- Browser: Chrome
- Browser version: 111
- Website version: V2
  (As displayed on the site top navigation)

## Additional info

The result of https://github.com/mi6/ic-design-system/pull/372 will determine whether the fix is required on the guidance site or to the component.

**Comment by ASM995** [comment]
Issue has been fixed.
