### ISSUE TITLE
'Success Alert' example in the 'Alert' component guidance

### ISSUE THREAD

**Issue by gd2910** [mi6/ic-design-system#394]
## Summary

Consider adding 'Success Alert' guidance in the 'Alert' component guidance.

## 💬 Description

In the 'Success messages' design pattern guidance there is a 'for example' link to the 'Alert' component guidance but the guidance does not contain information on success messages best practices.
https://design.sis.gov.uk/patterns/success

Definition of done is when the 'Alert' component guidance contains information on using a success alert, or alternatively, the Success Messages patterns page includes an example of this.
https://design.sis.gov.uk/components/alerts
 
## 💰 Use value

A User is correct to assume that there will be an example or use case for 'success messages' when following the link.

## Additional info

Ticket will need to go through design.

**Comment by ASM995** [comment]
The success variants is referenced in the written guidance and displayed on the code page.
