### ISSUE TITLE
Interactive component code examples cause flashing turquoise in mobile view

### ISSUE THREAD

**Issue by gd2910** [mi6/ic-design-system#395]
## Summary of the bug

When interactive components examples are used on the site the component area flashes turquoise. After a little investigation this affects;
- Breadcrumb
- Card with interaction button
- Checkbox
- Data Entity
- Radio Button
- Switch

## 🪜 How to reproduce

1. Go to page: https://design.sis.gov.uk/components/switch#
2. Click on: the interactive Switch component
3. See the error

## 🧐 Expected behaviour

Should not flash turquoise when interacted with.

## Mobile

- OS: iOS
- Browser: Safari

**Comment by MI6-255** [comment]
Closed as only Switch as an issue, which will be addressed bu the ticket to reduce the click area
