### ISSUE TITLE
Select Component space bar default behaviour 

### ISSUE THREAD

**Issue by ASM995** [mi6/ic-design-system#406]
## Summary of the bug

The spacebar key usage is incorrect when a select dropdown is open. When the dropdown is open, the spacebar key still performs default browser behaviour of scrolling the page. It should instead perform the action of selecting the focused dropdown option and closing the select dropdown. 

## 🪜 How to reproduce

Go to Components. Go to Select page. Move focus to select. Press space bar to open select dropdown.  Whilst dropdown is open press 'space'. The site scrolls and nothing is selected in the select box. 

## 🧐 Expected behaviour

When select input is focussed, pressing space bar should open the dropdown. If no option is selected or focussed, pressing space bar again should close the select box without any option being selected. 

Whilst dropdown is open, if an option is focussed, pressing space should select that option and close the dropdown. 

Whilst dropdown is open, if an option is focussed, and that option is already selected, then the dropdown should close and the current selected option should remain selected. 

## 📸 Screenshots or code

If you can, add screenshots to show the problem. If you need to show a code example, you can include a snippet or link to a repository with an example.

## 🖥 Desktop

- OS: [e.g. macOS]
- Browser: Safari
- Browser version: [e.g. 22]
- Website version: [e.g. V1, V2]
  (As displayed on the site top navigation)

## 📱 Mobile

- Device: [e.g. iPhone13]
- Browser: [e.g. chrome, safari]
- Browser version: [e.g. 22]
- Website version: [e.g. V1, V2]
  (As displayed on the site top navigation)

## Additional info

Tell us anything else useful to help us fix or understand the problem.

**Comment by ad9242** [comment]
covered by https://github.com/mi6/ic-ui-kit/issues/541
