### ISSUE TITLE
Classification banner on 'Classification banner' page overlays footer content 

### ISSUE THREAD

**Issue by ASM995** [mi6/ic-design-system#412]
## Summary of the bug

Classification banner on 'Classification banner' page overlays footer content, hiding Crown copyright text.

## 🪜 How to reproduce

Go to Classification banner guidance page. 

## 🧐 Expected behaviour

Webpage should account for Classification banner height and not hide content.

## 📸 Screenshots or code

If you can, add screenshots to show the problem. If you need to show a code example, you can include a snippet or link to a repository with an example.

## 🖥 Desktop

- OS: [e.g. macOS]
- Browser: Chrome
- Browser version: [e.g. 22]
- Website version: [e.g. V1, V2]
  (As displayed on the site top navigation)

## 📱 Mobile

- Device: [e.g. iPhone13]
- Browser: [e.g. chrome, safari]
- Browser version: [e.g. 22]
- Website version: [e.g. V1, V2]
  (As displayed on the site top navigation)

## Additional info

Tell us anything else useful to help us fix or understand the problem.

**Comment by ad9242** [comment]
related to https://github.com/mi6/ic-ui-kit/issues/543
