### ISSUE TITLE
Top Navigation flickers at a certain screen size 

### ISSUE THREAD

**Issue by ASM995** [mi6/ic-design-system#425]
## Summary of the bug

At a screen size of 1006, the top navigation on the navigation page flashes continuously. 

## 🪜 How to reproduce

Set screen size to 1006, navigate to top navigation page, see top nav flash excessively.

## 🧐 Expected behaviour

No flashing 

## 📸 Screenshots or code

https://user-images.githubusercontent.com/113986285/234522277-1e367791-5f64-4025-82dd-273efa0701df.mov

## 🖥 Desktop

- OS: [e.g. macOS]
- Browser: Chrome
- Browser version: [e.g. 22]
- Website version: [e.g. V1, V2]
  (As displayed on the site top navigation)

## 📱 Mobile

- Device: [e.g. iPhone13]
- Browser: [e.g. chrome, safari]
- Browser version: [e.g. 22]
- Website version: [e.g. V1, V2]
  (As displayed on the site top navigation)

## Additional info

Tell us anything else useful to help us fix or understand the problem.

**Comment by GCHQ-Developer-847** [comment]
After a team discussion, it seems this is probably related to the ic-horizontal-scroll (possibly the resize observer in particular), as the top navigation is switching between the scrolling and non-scrolling variant when it is flickering. Deleting the first code example stops the flickering from happening, and this is the one which has the most navigation items so has the scroll buttons of the ic-horizontal-scroll appearing.
