### ISSUE TITLE
Scroll to top causes everything to render big then shrink small 

### ISSUE THREAD

**Issue by ASM995** [mi6/ic-design-system#426]
## Summary of the bug

Using scroll to top causes a rendering issue when refreshing the website. 

## 🪜 How to reproduce

On iPhone, scroll to top to trigger a refresh, notice how the arrow gets larger then resizes to its normal size.

## 🧐 Expected behaviour

Should not flash

## 📸 Screenshots or code

If you can, add screenshots to show the problem. If you need to show a code example, you can include a snippet or link to a repository with an example.

## 🖥 Desktop

- OS: [e.g. macOS]
- Browser: [e.g. chrome, safari]
- Browser version: [e.g. 22]
- Website version: [e.g. V1, V2]
  (As displayed on the site top navigation)

## 📱 Mobile

- Device: iPhone XR
- Browser: Safari
- Browser version: [e.g. 22]
- Website version: [e.g. V1, V2]
  (As displayed on the site top navigation)

## Additional info

Tell us anything else useful to help us fix or understand the problem.

**Comment by MI6-255** [comment]
Fixed
