### ISSUE TITLE
Review code examples on Guidance Site

### ISSUE THREAD

**Issue by GCHQ-Developer-741** [mi6/ic-design-system#434]
## What is the purpose of the work?
Current code examples vary in how much they need to be edited once pasted into an editor. Some work straight away but others produce errors which require changes. Also, for TypeScript codebases, our examples can throw type errors. We could offer regular JavaScript + TypeScript code examples, by adding an extra tab to the code snippets.

## Why do we need it?
This disrupts the workflow of people wanting to get started developing with our components who are unfamiliar with them. We want to make it as easy as possible to implement components.

**Comment by ASM995** [comment]
Ticket linked to #321
