### ISSUE TITLE
Update the "Create check-versions Pull Request" step of the automated release

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-design-system#479]
## Summary of the bug

At the moment, the automated release fails because it can't create a check-versions -> develop PR. It looks like it can't find a check-versions branch, but this shouldn't be an issue as the create-pull-request action it uses should make a new branch called check-versions. 

Someone else has had the same problem and created an issue on the action's github, but there is no fix on there as of yet and it seems it might be an issue with their repo, not the action. https://github.com/peter-evans/create-pull-request/issues/1914

## 🪜 How to reproduce

Tell us the steps to reproduce the problem:

1. Go to actions tab
2. Click on: Check versions
3. See it fails

## 🧐 Expected behaviour

It should create a check-versions -> develop PR.

## 📸 Screenshots or code

<img width="748" alt="Screenshot 2023-05-22 at 15 57 46" src="https://github.com/mi6/ic-design-system/assets/111882034/413b0848-6ae6-4270-990b-bf49c7270024">

**Comment by peter-evans** [comment]
I saw this linked to an issue and took a look. I think the problem is that you are creating a local branch called `check-versions` before the action is run. You don't need to do that. The action will create it for you.

Please try the following changes:
```diff
    steps:
      - uses: actions/checkout@v3
+       with:
+         ref: develop
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: browser-actions/setup-chrome@latest
      - name: Install latest components
        run: |
-         git fetch
-         git checkout develop
-         git checkout -b check-versions develop
          DOCS_VERSION=$(npm view @ukic/docs version)
          FONTS_VERSION=$(npm view @ukic/fonts verion)
          REACT_VERSION=$(npm view @ukic/react version)
          WEB_COMPS_VERSION=$(npm view @ukic/web-components version)
          npm install @ukic/docs@$DOCS_VERSION @ukic/fonts@$FONTS_VERSION @ukic/react@$REACT_VERSION @ukic/web-components@$WEB_COMPS_VERSION --legacy-peer-deps
      - name: Create check-versions Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "check-versions -> develop"
          commit-message: "chore(root): Update to latest versions"
          body: "Github action updated package versions"
          branch: check-versions
          base: develop
```

**Comment by GCHQ-Developer-530** [comment]
Thank you so much @peter-evans! I will give that a try now 👍
