### ISSUE TITLE
Update tooltip guidance to include updated tooltip styling as well as examples that include icons. 

### ISSUE THREAD

**Issue by DBD324** [mi6/ic-design-system#484]
## Summary

The tooltip guidance page needs updating to reflect latest changes to tooltip designs. 

## 💬 Description

The tooltip imagery should be updated to use the latest designs that include the white outline. 
Sections should be added to the guidance to talk about the ability of adding icons to tooltips. 

## 💰 Use value

Update required to reflect latest component changes. 

## Additional info

Tell us anything else useful to help us understand your suggestion.

**Comment by GCHQ-Developer-094** [comment]
Latest site guidance shows this as complete.
