### ISSUE TITLE
[ic-breadcrumbs]: Slotted variant styling incorrect.

### ISSUE THREAD

**Issue by jd239** [mi6/ic-design-system#490]
## Summary of the bug
When using slots to pass through an `<a>` into a breadcrumb, the styling does not mirror the IcLink. The styling used is the generic hyperlink style provided by the browser. 

## 🪜 How to reproduce
Tell us the steps to reproduce the problem:
1. Go to page: 'https://design.sis.gov.uk/components/breadcrumbs/code'
2. View 'With React Router' example

## 🧐 Expected behaviour
Styling on breadcrumbs should be the same as examples above and IcLink.

## 📸 Screenshots or code
![Capture](https://user-images.githubusercontent.com/116016939/229144744-aeb1f4eb-f40a-443e-b8b4-6d757e5ca35c.PNG)

Code Example:

```jsx
<IcBreadcrumbGroup>
  <IcBreadcrumb pageTitle="Home">
    <NavLink to="/">Home</NavLink> // Imported from react-router-dom
  </IcBreadcrumb>
  <IcBreadcrumb pageTitle="Beverages">
      <NavLink to="/">Beverages</NavLink>
    </IcBreadcrumb>
</IcBreadcrumbGroup>
```

## 🖥 Desktop
 - OS: Windows
 - Browser: Chrome
 - Version: 110

## 📱 Mobile
 - Device: [e.g. iPhone13]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

## Additional info
There may be an issue with the styling on a `::slotted(a)` style

**Comment by ASM995** [comment]
Work complete.
