### ISSUE TITLE
Component list needs restructuring into alphabetical order

### ISSUE THREAD

**Issue by gd2910** [mi6/ic-design-system#491]
## Summary of the bug

Top Nav component should come before Typogrpahy

## 🪜 How to reproduce

1. Go to page: [Component List](https://design.sis.gov.uk/components)
2. Scroll to bottom of component list

## 🧐 Expected behaviour

Top Navigation should precede Typography

## 🖥 Desktop

- OS: [e.g. macOS]
- Browser: [e.g. chrome, safari]
- Browser version: [e.g. 22]
- Website version: [e.g. V1, V2]
  (As displayed on the site top navigation)

## 📱 Mobile

- Device: [e.g. iPhone13]
- Browser: [e.g. chrome, safari]
- Browser version: [e.g. 22]
- Website version: [e.g. V1, V2]
  (As displayed on the site top navigation)

## Additional info

Tell us anything else useful to help us fix or understand the problem.

**Comment by KMArtwork** [comment]
Hi I would love to help resolve this issue for you!
