### ISSUE TITLE
Layout Template for ic-top-navigation

### ISSUE THREAD

**Issue by gd2910** [mi6/ic-design-system#493]
## Summary

Create an external layout template to showcase ic-top-navigation in a more native full screen/content pattern

## 💬 Description

With reference to ic-side-navigation, create a separate page with a react style small app showcasing ic-top-nav.
ic-side-navigation can be used as reference for this. The page will need to be added to gatsby-browser.js to ensure the main template is not applied. 

## 💰 Use value

A functional example of ic-top-navigation will help developers utilise the component.

## Update
This work will be addressed with the new [top navigation pattern examples](https://github.com/mi6/ic-design-system/issues/760). This ticket should focus on adding a section to the top nav code page and redirect users to the top navigation pattern page

**Comment by GCHQ-Developer-112** [comment]
This relates #760
