### ISSUE TITLE
Footer beneath the page fold information 

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-design-system#551]
## Summary of the bug

There is guidance on putting the footer under the page fold, however there is no demo on how to achieve this. It would be good to show how to do this.  

## 🪜 How to reproduce
[This page](https://design.sis.gov.uk/components/footer#placement ) needs updating or a new page about the page fold should be created. 

## 🧐 Expected behaviour

A page or a section on the footer page to state the reasons why the footer should be beneath the page fold and how to do it. 

Having additional guidance such as "place main content to take up the remainder of the screen by using `flex-grow: 1`"

## 📸 Screenshots or code
<img width="835" alt="Screenshot 2023-07-27 at 10 31 08" src="https://github.com/mi6/ic-design-system/assets/111882114/4122c003-f550-49a8-b565-1be521734d90">

**Comment by Project-4040** [comment]
Surely the footer is below the fold by its very nature?

**Comment by GCHQ-Developer-465** [comment]
Yes of course, however more guidance for users would be great, so that they know how to do this and why. Thanks :)

**Comment by DBD324** [comment]
Update 'code' page to include variant demonstrating how to achieve footer positioning below the folds.
