### ISSUE TITLE
Textfield guidance on error validation is not up to date 

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-design-system#552]
## Summary of the bug

The [textfield guidance](https://design.sis.gov.uk/components/text-input#validation-error-handling) is not up to date with the code validation. The error text is in red, whereas the code is now in normal text. 

## 🪜 How to reproduce

1. Go to page: https://design.sis.gov.uk/components/text-input#validation-error-handling
2. Now go to page: https://design.sis.gov.uk/components/text-input/code/#validation
3. See the error 

## 🧐 Expected behaviour

The image on https://design.sis.gov.uk/components/text-input#validation-error-handling needs to be updated so that the guidance and code are consistent. 

## 📸 Screenshots or code
<img width="362" alt="Screenshot 2023-07-27 at 11 10 46" src="https://github.com/mi6/ic-design-system/assets/111882114/a888237b-fa54-468f-b724-06a35b6fcf9d">
<img width="402" alt="Screenshot 2023-07-27 at 11 10 55" src="https://github.com/mi6/ic-design-system/assets/111882114/c1a82497-dd95-435d-9303-5b51caeb9d59">

**Comment by ASM995** [comment]
Closing ticket as work has been completed in #483
