### ISSUE TITLE
Component page tabs changing content before refresh

### ISSUE THREAD

**Issue by GCHQ-Developer-741** [mi6/ic-design-system#553]
## Summary of the bug
The code, accessibility and guidance tabs were recently updated to navigate to a new page on click (https://github.com/mi6/ic-design-system/pull/503). However, this behaviour clashes with older behaviour where the page would be updated by changing local state with the new markdown for the page, allowing for updating without navigation.

Because of this, when clicking between the tabs, it changes the content locally before immediately refreshing the page, leading to flashing and moving content.

## 🪜 How to reproduce
1. Go to page: https://design.sis.gov.uk/components/alerts
2. Click on the 'code' tab
4. See the error

## 🧐 Expected behaviour
The local state changes are a bit obsolete and not really in line with what we want, so really they can be removed.
See [here](https://github.com/mi6/ic-design-system/blob/6221b80fdf853be491ea46a65dbe4f80adf24247/src/templates/CoreTemplate/index.tsx#L49) for where the state is being set

## 📸 Screenshots or code
[Screencast from 27-07-23 12:16:15.webm](https://github.com/mi6/ic-design-system/assets/117368893/170c6146-eb2e-4df1-acc9-4219a787162b)

**Comment by GCHQ-Developer-299** [comment]
If we're sticking with using the header 'tabs' as links, we could add a new "Skip to Tab Content" link at the top of the page immediately after the main "Skip to Content" link

But i'm hearing (and sharing) the preference towards making them proper tabs, so the page doesn't reload and focus isn't lost.

**Comment by GCHQ-Developer-741** [comment]
Is being closed as part of the work done in https://github.com/mi6/ic-design-system/issues/563
