### ISSUE TITLE
Update to how 'Components' pages navigate between pages

### ISSUE THREAD

**Issue by GCHQ-Developer-741** [mi6/ic-design-system#563]
## Summary
Currently, the Page Header on all Components pages feature three navigation-items; 'Guidance', 'Code', 'Accessibility'. These function as nav items to three seperate pages, which enables having anchor links for subheadings which can be navigated to individually.

The original intention of ic-page-header involved using tabs rather than navs, since it would allow for the focus to be kept on the page whilst being able to quickly navigate between content. However, there have been issues in the past around the anchor links not working when this was implemented (https://github.com/mi6/ic-design-system/pull/503)

## 💬 Description
The nav items should be made to function like tabs, in order to provide a better user experience when navigating between content. This includes:

- Having one single URL for the three tabs (removing /code and /accessibility)
- Changing the permalinks next to each subheading to copy the url to the clipboard, rather than jump to the subheading.
- The anchor nav on the side of each page should jump to the heading when an option is clicked (like the current implementation)
- When a copied URL for a permalink is entered and searched for, it should place the user at the top of the permalink's corrosponding tab, with focus on the tab, to allow the user to quickly access the anchor nav to reach their intended subheading.

## 💰 Use value
This will aid smoother navigation between pages and help the application function more like tabs which was originally intended.

## Additional info
The PR linked above would need to be reverted, as the behaviour before this included the tab-like behaviour.

This makes https://github.com/mi6/ic-design-system/issues/553 redundant. The issue will be closed.

**Comment by jd239** [comment]
Things to try:
- Revert back to using the tab concept instead of switching between pages
- Move the links out of page header and use a separate tab component below
- Take out left over tab concept from previous work. Use page load and when page has loaded, use JS to focus on clicked element
