### ISSUE TITLE
Add guidance for importing ICDS CSS files for Storybook

### ISSUE THREAD

**Issue by GCHQ-Developer-112** [mi6/ic-design-system#574]
## Summary

Add some guidance on importing the ICDS CSS files into the `preview.ts` or `preview.js` file when using Storybook

## 💰 Use value

Storybook is common tool used for front-end development. It would be helpful to have some guidance on importing ICDS CSS files for Storybook so we can direct people to this guidance when they ask

**Comment by ASM995** [comment]
Closing as out of team's scope.
