### ISSUE TITLE
Investigate concurrency for github workflows

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-design-system#6]
## Summary
Explore and add concurrency to our github workflows so that new builds don't cancel in progress builds.

## 💬 Description
Currently in ic-design-system-branches.yml and ic-design-system-main.yml, we have concurrency set using ${{ github.ref }}, however this doesn't seem to be working as it's cancelling in progress builds in favour of new builds (https://github.com/mi6/ic-design-system-githubpages/actions). This needs fixing so that multiple branches can build at once.

## 💰 Use value
It will save development time not having to re run builds due to them being cancelled.

## Additional info
The concurrency currently pauses the build on the design system side, but it's the githubpages repo that's causing the concurrency issues.

**Comment by jd239** [comment]
After investigating the concurrency issues, it became apparent that the `pages-build-deployment` action is part of the GitHub pages deployment. This GitHub action was causing the most trouble as deployments would often be cancelled if another deployment was to start.

One way around that was to look at a custom workflow for pages deployment. Unfortunately, was unable to find a GitHub action which allowed the deployment of built assets into a particular subdirectory within the gh-pages repo.

The PRs created for this ticket include an update to the deployment github actions we have control of. The concurrency functionality will now cancel a build if codebase from the same branch is pushed up while a previous build (from the same branch) is running.
