### ISSUE TITLE
Improve Typography documentation

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-design-system#621]
## Summary

Improve Typography documentation examples to make it clear h1 tags should be used semantically, how and in what ways. 

## 💬 Description

This issue should:

- Include more code examples
- Document the difference between styling and semantic heading elements
- Link to when you use different heading elements

## 💰 Use value

Make it clear to consumers that the HTML heading tags should be used alongside stlying options.

**Comment by GCHQ-Developer-299** [comment]
PR Merged, closing ticket :)
