### ISSUE TITLE
update accessibility guidance for tooltips

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-design-system#622]
## What component is this related to?
ic-tooltip

## Why do we need it?

Following changes to tooltips under https://github.com/mi6/ic-ui-kit/issues/860, the guidance should be updated to reflect the changes made. In particular, may want to reference the new `silent` prop.

**Comment by ASM995** [comment]
Dependent on https://github.com/mi6/ic-ui-kit/issues/1227 being completed.
