### ISSUE TITLE
Update all dev mode figma component links to the guidance site to ensure they are pointing at the right page

### ISSUE THREAD

**Issue by ASM995** [mi6/ic-design-system#627]
## What component is this related to?

Top Nav, Side nav, toast, tooltip, any component that has a common shortened version (e.g. top nav instead of top navigation) or uses a plural (tooltips instead of tooltip). Haven't checked every component yet though.

## Why do we need it?

When handing over from designer to dev mode on Figma there is an option to click a link that takes you straight to the guidance site for that component. On a lot of the components, this link is broken and results in not taking you to the component page but to an error page saying it doesn't exist. This is just an issue with the link itself as it is named incorrectly.

## Related open issues

[Link to other GitHub issues]

**Comment by GCHQ-Developer-094** [comment]
Now merged into master file
