### ISSUE TITLE
Incorrect code snippet for ic-dialog

### ISSUE THREAD

**Issue by GCHQ-Developer-741** [mi6/ic-design-system#648]
## Summary of the bug
The code snippet for ic-dialog, under the "Interactive Content" heading, the React example should include an onIcDialogConfirmed event listener.

## 🧐 Expected behaviour
```
<IcDialog ref={dialogEl} label="Coffee order"
  heading="Please agree to our terms and conditions"
  onIcDialogConfirmed={termsDialogConfirmed}
>
```

**Comment by MI6-255** [comment]
Is this done @MI6-94 ?

**Comment by MI6-94** [comment]
@MI6-255 did not complete, return to 'ready for dev'

**Comment by GCHQ-Developer-741** [comment]
Completed as part of a seperate check of the code examples
