### ISSUE TITLE
Page header hides top of sections when clicking on an anchor / heading link

### ISSUE THREAD

**Issue by GCHQ-Developer-847** [mi6/ic-design-system#651]
## Summary of the bug

If you click on a link next to a heading on a page on the website (or just enter a URL which is a link directly to one of the headings - i.e. containing a '#'), it goes to the section on the page but it gets partly hidden at the top by the page header. It might be a bit confusing to the user at first as they may wonder if it has jumped to the correct section if they can't see the heading (until they scroll up).

## 🪜 How to reproduce

1. Go to a URL which takes you directly to a specific heading, e.g. https://design.sis.gov.uk/components/button#when-to-use
2. See how the top part of the section (the heading and first few lines) is hidden by the page header

## 📸 Screenshots or code

This is what it looks like straight after clicking on the 'When to use' heading link (or clicking the link above)

![image](https://github.com/mi6/ic-design-system/assets/111882109/63206755-d494-49cc-b19f-5615d534d1da)

The page header covers the top of the section.

## 🖥 📱 Device

- Type: Desktop
- Browser version: Chrome 118

## 🧐 Expected behaviour

It would be better if the page were to jump to just above the heading, allowing enough space for the page header with the heading positioned just underneath.

## Additional info

Could a solution be to just make the page header on the website not sticky?

**Comment by ASM995** [comment]
This will be delivered by the upcoming Table of Contents component.

**Comment by GCHQ-Developer-847** [comment]
When the Table of Contents component has been created, a ticket will need to be raised to replace the current anchor nav on the website with the new component. That will resolve this issue.

**Comment by ASM995** [comment]
Linked to: https://github.com/mi6/ic-ui-kit/issues/752
