### ISSUE TITLE
Explore FOUC on the website and components

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-design-system#654]
## Summary

Explore Flash of Unstyled Content (FOUC) on the website and components, to understand and document why it is happening and consider potential fixes.

## 💬 Description

The spike is the initial SSR exploration to:

- understand why the website flashes
- how we fix our website
- what guidance we need to offer to consumers for Gatsby, Next.js etc 
- why other libraries do not have this issue e.g. Duet (built with Stencil) and narrow down what we're doing differently to fix it (e.g. potentially start fresh and keep re-introducing ICDS code until we find the issue)
- research online how others using Stencil/web components get around SSR at the minute 
- begin to document our understanding, so we can amend it over time

It would be suggested to have a minimum of a 5 day exploration. 

I do have a consumer who has an example app we can look at which uses SSR and does not flicker, please consult the internal log related to this issue.

## 💰 Use value

Describe why this is important and how it will help users (either developers, designers or the end-users). Think about how it makes people's lives easier, more accessible or quicker to build stuff.

**Comment by MI6-255** [comment]
See internal log for surrounding notes

**Comment by GCHQ-Developer-847** [comment]
See [my comment on another FOUC-related ticket](https://github.com/mi6/ic-ui-kit/issues/1415#issuecomment-1997155336)
