### ISSUE TITLE
[ic-design-system]: Console errors about ic-tooltip and innerText

### ISSUE THREAD

**Issue by GCHQ-Developer-112** [mi6/ic-design-system#660]
## Summary of the bug
There are console errors on every page on the website about `ic-tooltip` and `innerText`.

## 🪜 How to reproduce
Open dev tools and look at the console.

## 🧐 Expected behaviour
There should be no errors

Raised by: @GCHQ-Developer-847

**Comment by ad9242** [comment]
will be fixed by https://github.com/mi6/ic-ui-kit/issues/1204
