### ISSUE TITLE
Select custom filtering example shows 'no results' even when there are results

### ISSUE THREAD

**Issue by DBD324** [mi6/ic-design-system#663]
## Summary of the bug

On teh select code guidance page the custom filtering example shows 'no results' when initially focussed. After typing results are then returned that match teh search string. This is incorrect as there are results available initially, the search just hasbn't been performed yet. 

## 🪜 How to reproduce

Tell us the steps to reproduce the problem:

1. Go to page: 'Select/Code'
2. Scroll to custom filtering example. 
3. Click on select box in code example
4. See the 'no results' in the dropdown list. 

## 📸 Screenshots or code

![image](https://github.com/mi6/ic-design-system/assets/116820773/6e9b96d3-6f30-4777-a091-18cf9c178860)

## 🖥 📱 Device

- All

## 🧐 Expected behaviour

When focussed, no droplist should display. After the search term is entered, then the results should be displayed if extant, otheriwse the no results state should be displayed. 

## 📝 Acceptance Criteria

If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.

_Given_ that a searchable select field exists on a page
_When_  it is intially focussed
_Then_ the 'no results' state should not display. 

## Additional info

Tell us anything else useful to help us fix or understand the problem.

**Comment by ASM995** [comment]
Closing as work will be delivered in https://github.com/mi6/ic-ui-kit/issues/1207
