### ISSUE TITLE
[Guidance]: Title of "Get the components" in left hand nav should be changed

### ISSUE THREAD

**Issue by GCHQ-Developer-112** [mi6/ic-design-system#666]
## What component is this related to?

"Get the components" accordion in the ["Get started"](https://design.sis.gov.uk/get-started) section of the guidance site

## Why do we need it?
A title that's clearer than 'Get the components' could help with site navigation and better describe the child pages within this page. 

Suggestion (from @GCHQ-Developer-112): "Install the components" instead of "Get the components". 

Raised on behalf of: @GCHQ-Developer-465

**Comment by MI6-255** [comment]
Agreed @GCHQ-Developer-112 would split this up, and take the moving of the Page to a new ticket, which could come under the re-structuring issue
