### ISSUE TITLE
Links in markdown do not utilise GatsbyLink

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-design-system#672]
## Summary of the bug

Links in markdown do not utilise GatsbyLink, meaning they trigger a hard refresh

## 🪜 How to reproduce

Tell us the steps to reproduce the problem:

1. Go to the "Styles" page
2. Click on any link such as "Component"

## 🧐 Expected behaviour

Expect the page to not fully refresh and utilise the Gatsby routing.

## Additional info

This is replicated throughout a lot of the site and might not be exclusive to GatsbyLinks.

**Comment by ASM995** [comment]
Closing ticket as not currently an issue.
