### ISSUE TITLE
Switch steps four/five on Getting started

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-design-system#689]
## Summary

Switch steps four/five on Getting started

## 💬 Description

The order of the instructions likely should read to set the CSS first, then test a component after. This is evident in the Svelte instructions and other getting started instructions.

## 💰 Use value

Make it easier for people to get started without bugs

**Comment by jd239** [comment]
This has been complete here: https://github.com/mi6/ic-design-system/pull/687
