### ISSUE TITLE
Logo on mobile view is no longer navigating the user back to the homepage

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-design-system#708]
## Summary of the bug

The logo on mobile view is no longer clickable. The logo used to be clickable and navigate users to the home page. Now that no longer works and the user struggles to navigate to home page. 

## 🪜 How to reproduce

Tell us the steps to reproduce the problem:

Ensure your are viewing the site on mobile view. 
1. Go to a page that is not the home page e.g. Accessibility
2. Click on the logo 
3. See the error

## 🖥 📱 Device

- Type: mobile

## 🧐 Expected behaviour

The logo should redirect the user to the home page.

**Comment by ad9242** [comment]
@GCHQ-Developer-465 this seems to be working ok now - can you still recreate it?

**Comment by jd239** [comment]
Ticket now includes checking IcSideNavigation component as well.

**Comment by GCHQ-Developer-465** [comment]
> @GCHQ-Developer-465 this seems to be working ok now - can you still recreate it?

Looks like this is working now. I will be testing the IcSideNavigation as @jd239 has mentioned below.

**Comment by GCHQ-Developer-465** [comment]
After more exploration with this I have come to the conclusion that this is no longer an issue. I tested the Side Navigation on a live application and it works as it should. Therefore have closed this issue.
