### ISSUE TITLE
Popover menu not displaying some items in component preview

### ISSUE THREAD

**Issue by MI6-94** [mi6/ic-design-system#719]
## Summary of the bug

The popover menu is not displaying some items correctly. It appears to be lack of contrast on some nav items.

## 🪜 How to reproduce

Tell us the steps to reproduce the problem:

1. Go to page: https://design.sis.gov.uk/components/popover-menu
2. Look at the component preview (the first one on guidance tab but is others)
3. See the error

## 📸 Screenshots or code

<img width="759" alt="Screenshot 2023-12-11 at 11 45 11" src="https://github.com/mi6/ic-design-system/assets/90764530/af517245-7f0b-43fc-bd84-b02958b155da">

## 🧐 Expected behaviour

All the items in the popover menu should be visible.

This issue may also be related the styling not appearing correctly for the menu items For example, the text for each menu item is using `Action Blue` when it should be black if not highlighted. Destructive items (e.g. DELETE) should also appear in red.

![image](https://github.com/mi6/ic-design-system/assets/116016939/45e32af1-c38d-48aa-9f5b-25346ef6e0c2)

**Comment by jd239** [comment]
Bug can be recreated in Safari
