### ISSUE TITLE
[ic-classification-banner]: Guidance update required for clasification

### ISSUE THREAD

**Issue by jd239** [mi6/ic-design-system#721]
## What component is this related to?

ic-classification-banner

## Why do we need it?

There is a paragraph about the use of the classification banner when exporting a page or printing out a page. This needs to be reviewed as it may not be technically possible.

![image](https://github.com/mi6/ic-design-system/assets/116016939/e92a5527-e9fb-4b22-a2df-f8c0567fda6b)

## Related open issues

Linked to: https://github.com/mi6/ic-ui-kit/issues/1317

**Comment by ASM995** [comment]
This ticket is to remove the second paragraph in the screenshot above.
