### ISSUE TITLE
Compilation errors in Angular 17

### ISSUE THREAD

**Issue by GCHQDeveloper1138** [mi6/ic-design-system#736]
## Summary of the bug

When used with Angular 17, ICDS types file cannot be compiled due to a conflict of properties due to multiple inheritance (see error below)

The app will not compile as a result

## 🪜 How to reproduce

Starting with an Angular 17 application, follow the instructions here: https://design.sis.gov.uk/get-started/install-components/angular

(Note that for an app with standalone components, the CUSTOM_ELEMENTS_SCHEMA will need to be added to components, not the module)

run 'ng serve' to serve the app and the error should occur

## 📸 Screenshots or code

Error is as follows:
```
⠧ Building...✘ [ERROR] TS2320: Interface 'HTMLIcTextFieldElement' cannot simultaneously extend types 'IcTextField' and 'HTMLStencilElement'.
  Named property 'ariaExpanded' of types 'IcTextField' and 'HTMLStencilElement' are not identical. [plugin angular-compiler]

    node_modules/@ukic/web-components/dist/types/components.d.ts:2659:14:
      2659 │     interface HTMLIcTextFieldElement extends Components.IcTextFi...
           ╵               ~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] TS2320: Interface 'HTMLIcTextFieldElement' cannot simultaneously extend types 'IcTextField' and 'HTMLStencilElement'.
  Named property 'role' of types 'IcTextField' and 'HTMLStencilElement' are not identical. [plugin angular-compiler]

    node_modules/@ukic/web-components/dist/types/components.d.ts:2659:14:
      2659 │     interface HTMLIcTextFieldElement extends Components.IcTextFi...
           ╵               ~~~~~~~~~~~~~~~~~~~~~~

```

## 🖥 📱 Device

- Type: Desktop
- Device: Macbook
- OS version: MacOS Sonoma 14.2
- Browser version: N/A
- Angular version: 17

## 🧐 Expected behaviour

The app should compile without the error

## 📝 Acceptance Criteria

If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.

_Given_
_When_  
_Then_

## Additional info

I did a bit of Googling and found a similar error afflicting other projects. It can be worked around by turning off some TypeScript features, and may be related to stricter compilation rules in TypeScript >= 4.4.3 (see https://github.com/ionic-team/ionicons/issues/1011 and https://github.com/ionic-team/ionicons/issues/1007)

**Comment by GCHQ-Developer-847** [comment]
The solution for this has been found - I have created a ticket to get it added to the Angular instructions on the ICDS website: #737.
