### ISSUE TITLE
Side nav loses focus when you select an anchor link

### ISSUE THREAD

**Issue by GCHQ-Developer-112** [mi6/ic-design-system#74]
## Summary of the bug
On some pages, the side nav loses focus when you select an anchor link or when you select a subheading in the right hand side nav on the page.

## 🪜 How to reproduce
1. This issue can be found on all pages except the individual component pages e.g. the issue can't be seen on: the [chips component page](https://design.sis.gov.uk/components/chips) but it can be seen on the overarching [components page](https://design.sis.gov.uk/components)

2. Select an anchor link or select a subheading in the right hand side nav on the page

## 🧐 Expected behaviour
Expect the side nav to keep focus when I select an anchor link or select a subheading in the right hand side nav on the page.

## 📸 Screenshots or code
<img width="1440" alt="Screenshot 2022-11-24 at 12 17 56" src="https://user-images.githubusercontent.com/113986285/203782655-d9db7be4-27df-443e-bcae-40ca348744a9.png">

## 🖥 Desktop
 - OS: macOS
 - Browser: Chrome 107

**Comment by ASM995** [comment]
@GCHQ-Developer-112 can you please confirm if this is still an issue, cant seem to replicate.

**Comment by GCHQ-Developer-112** [comment]
@ASM995 For the most part this issue has been solved. However, a few instances where the last heading on the anchor nav is never selected.

Examples:
- https://design.sis.gov.uk/get-started/design-principles/#transparent-and-open
- https://design.sis.gov.uk/components/#contribute

**Comment by GCHQ-Developer-112** [comment]
@ASM995 Yes this is still an issue. When you select an item using the right hand nav, the current page in the left hand nav loses focus

**Comment by MI6-94** [comment]
Linked to #298

**Comment by ASM995** [comment]
closed as duplicate ticket.

**Comment by DBD324** [comment]
Will be delivered by https://github.com/mi6/ic-ui-kit/issues/752
