### ISSUE TITLE
Footer and Hero navigates user to 'When to use' section 

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-design-system#740]
## Summary of the bug

The Footer and Hero navigates the user to 'When to use' which is not correct as it should start the user at the top of the page. 

## 🪜 How to reproduce

Tell us the steps to reproduce the problem:

1. Select 'Footer/Hero' from the side nav
2. See the error

## 📸 Screenshots or code
![Screenshot 2023-12-20 at 10 19 23](https://github.com/mi6/ic-design-system/assets/111882114/6fc2d364-7cdb-4d07-b224-7c6eebf839d3)
![Screenshot 2023-12-20 at 10 19 31](https://github.com/mi6/ic-design-system/assets/111882114/6581261d-2bd0-4a2f-9219-af0da312e688)

https://github.com/mi6/ic-design-system/assets/111882114/b47485ba-31fa-44c6-aa58-64eb29e57720

## 🧐 Expected behaviour

When the user navigates to these components on the site the user should not be navigated to the 'When to use' section. It should start the user at the top of the page with 'Introduction' like the other components.

**Comment by MI6-94** [comment]
Can't reproduce error on Safari or Chrome.
