### ISSUE TITLE
Add stackblitz button to component demos

### ISSUE THREAD

**Issue by DBD324** [mi6/ic-design-system#751]
## Summary

A new button should be added to the component demos that can be used to launch stackblitz demos of component demos.  

## 💬 Description

Component demos should be edited to allow a stackblitz button to be included and launch a stackblitz of the component demo. 

Explore whether an icon button would suffice, or if a labelled button is required. 

Button should be configurable so that different icons can be used to launch different types of code demos if stackblitz needs to be changed. 

Clicking the button should always open the demo in a new tab instead of in the existing window. 

The button should use stackblitz's iconography, but styled within an ICDS button. 

## 💰 User value

Allows developers to open a customisable code demo to experiement with component. 

## 📚 User Stories

If relevant, describe the high-level functionality as user stories.

_As an_ ICDS user:  
_I need_ a way to open a stackblitz link from a component demo
_So that_ I can view the full code example in stackblitz.

## 📝 Acceptance Criteria

If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.

_Given_ that a component demo is being configured,
_When_  setting it up
_Then_ an option exists to include a stackblitz link,
_and_ if selected a stackblitz button is rendered in the bottom bar next to the copy code button. 

_Given_ that a comp demo exists with a stackblitz button,
_When_ the viewport width is changed to the Md, Sm, or Xs, breakpoint,
_Then_ the stackblitz labelled button should be replaced with the stackblitz icon button,
_And_ the copy code button should follow the same behaviour. 

_Given_ that a comp demo exists with a stackblitz button,
_When_ the viewport width is changed to the Lg or Xl breakpoint,
_Then_ the stackblitz icon button should be replaced with the stackblitz labelled button,
_And_ the copy code button should follow the same behaviour. 

_Given_ that a comp demo exists with a stackblitz button,
_When_ the button is clicked, or otherwise actioned,
_Then_ it should open the stackBlitz link in a new tab. 

_Given_ that a comp demo exists with a stackblitz button,
_When_ navigated to using a SR,
_Then_ it should be announced as a button with accessible label "Open code example in StackBlitz"

## ✏ Designs

Please see the 'Component Library - ICDS Guidance Site' Figma file for visual designs. 

## 🧾 Guidance
N/A

## Additional info

Tell us anything else useful to help us understand your suggestion.

**Comment by MI6-255** [comment]
Consider if the platform choice is appropriate (the SDK may help), but would a website embedded version work better? Failing that, if there is not the SDK token, display the code on a plain screen

**Comment by MI6-255** [comment]
This is to be published once all components have been moved over to the SDK. This issue includes both the adding of the button, and working through each code example to get it to a good state. This work has been started as part of the patterns work.

**Comment by GCHQ-Developer-112** [comment]
## Components
These are a list of all of our components to be reviewed to ensure they are formatted correctly and work in StackBlitz
- [x] Accordion
- [x] Alert
- [x] Back to top
- [ ] Badge
- [ ] Breadcrumb
- [ ] Button
- [ ] Card
- [ ] Checkbox
- [ ] Chip
- [x] Classification banner
- [ ] Data entity
- [ ] Dialog
- [ ] Empty state
- [x] Footer
- [x] Hero
- [x] Link - import memory router, navlink
- [x] Loading indicator
- [x] Page header
- [x] Pagination
- [ ] Popover menu
- [x] Radio button
- [ ] Search bar
- [ ] Section container
- [ ] Select
- [ ] Side navigation
- [ ] Skeleton
- [ ] Status tag
- [x] Stepper
- [x] Switch
- [x] Tabs
- [x] Text field
- [ ] Toast
- [ ] Toggle button
- [x] Tooltip
- [ ] Top Navigation 
- [x] Typography

### Things to check for when reviewing these components:
- Does the code example need a parent container / fragment?
- Has any styling been moved into the long code?
- Has any script tags been moved into the long code and placed at the bottom of the code?
- All tags in web components code should have a closing tags - there are some exceptions e.g. `<img />`, `<meta />`
