### ISSUE TITLE
Side navigation layout pattern

### ISSUE THREAD

**Issue by GCHQ-Developer-485** [mi6/ic-design-system#764]
## Summary
Side navigation layout is a pattern used for quickly setting up a page that uses the side navigation.

## 💬 Description

It should be a fully functioning pattern that uses the following components 
The following component demos should be included:
- [ ] Side navigation layout (side navigation, section container, classification banner, footer)
- [ ] Side navigation layout with page header (side navigation, section container, classification banner, footer, page header)
- [ ] Side navigation layout with back to top (side navigation, section container, classification banner, footer, back to top)

## 💰 User value

Describe why this is important and how it will help users (either developers, designers or the end-users). Think about how it makes people's lives easier, more accessible or quicker to build stuff.

## 📚 User Stories

If relevant, describe the high-level functionality as user stories.

_As an_ ICDS user:  
_I need_
_So that_

## 📝 Acceptance Criteria

If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.

Given that a side navigation layout is being used
When the screen resizes
Then all components follow their responsive behaviours

Given the footer is on all of the patterns
When the patterns are initially opened
Then ensure the classification banner has been added at full width, at the bottom of each screen and is anchored

Given the footer is used on all patterns
When the user opens the page
Then ensure that the footer is always below the fold in it's entirety

Given there are two options for how the side navigation should appear at the extra-small breakpoints (collapsed or expanded)
When the extra-small breakpoint is used
Then default to the collapsed variant

_Given_
_When_  
_Then_

## ✏ Designs

Figma file ICDS UI kit Design Contributions -> Navigation pattern(NAV PATTERNS DESIGN!!! page)

## 🧾 Guidance
If there's written guidance or documentation, include a link to it here.

## Additional info

Tell us anything else useful to help us understand your suggestion.
#763 #765

**Comment by MI6-255** [comment]
Move across/delete the example on the Code page
