### ISSUE TITLE
Explore why the font flickers on a site refresh

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-design-system#779]
## Summary

Explore why the font flickers on a site refresh

## 💬 Description

On a hard refresh, the font flickers, despite not having to fetch it from the network. Explore how we prevent this flicker and if it's relevant to add more guidance, so that others do not have this issue.

Other projects using ICDS do not seem to have this.

## 💰 User value

The FOUC is not ideal for the experience of using the site.

**Comment by GCHQ-Developer-847** [comment]
See [my comment on another FOUC-related ticket](https://github.com/mi6/ic-ui-kit/issues/1415#issuecomment-1997155336)
