### ISSUE TITLE
NVDA issue with Cards 

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-design-system#780]
## Summary of the bug

When using NVDA screen reader the link is only announced and not the card description. 

## 🪜 How to reproduce

1. Go to page the [component gallery page](https://design.sis.gov.uk/components).
2. Use the NVDA screen reader
3. Navigate to one of the gallery cards using either the virtual cursor or the tab key. 
4. See that only the link is announced and not the card description. 

## 📸 Screenshots or code

TBA

## 🧐 Expected behaviour

The description of the card should be read out in the description.

**Comment by ASM995** [comment]
Closing as duplicate ticket.
