### ISSUE TITLE
Invalid code examples for Loading Indicator

### ISSUE THREAD

**Issue by GCHQ-Developer-257** [mi6/ic-design-system#822]
## Summary of the bug
One code example for Loading Indicator incurs an error when used, and there is no example given for the use of the description prop.

## 🪜 How to reproduce
Go to the Loading Indicator page and [head to Code](https://design.sis.gov.uk/components/loading-indicator/code), the sub-section titled **Light** gives this code example, that when run returns an error against the prop **name**. There is also no example for the use of description prop.
```
<IcLoadingIndicator type="circular" name="Loading" appearance="light" />
<IcLoadingIndicator type="linear" name="Loading" appearance="light"/>
```

## 📝 Acceptance Criteria
Correction of the error incurring **name** prop
Example of **description** prop

**Comment by MI6-255** [comment]
Where is the error?
