### ISSUE TITLE
Toggle button group guidance

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-design-system#826]
## What component is this related to?

Toggle button & toggle button group

## Why do we need it?

Currently there's guidance for toggle button on our site, including references to toggle button group. The majority of the guidance already exists for toggle button group, but there are no code examples.

This ticket involves:

- [x] - Adding code examples for toggle button group (this might mean replacing some of the toggle button code examples as we don't need both code examples for toggle button top icon, and a toggle button group with toggle buttons using top icon)
- [x] - Adding another component details table for toggle button group
- [x] - Removing the alert on the guidance page saying "toggle button group coming soon"
- [x] - Checking the accessibility guidance to ensure that it matches up with how toggle button group has been developed.

**Comment by GCHQ-Developer-465** [comment]
This is currently blocked by 748.

**Comment by GCHQ-Developer-465** [comment]
Have opened a PR for this but needs working on until [this PR](https://github.com/mi6/ic-ui-kit/pull/1537) goes in.
