### ISSUE TITLE
[canary]: Add Data Table documentation to Guidance site

### ISSUE THREAD

**Issue by jd239** [mi6/ic-design-system#861]
## What component is this related to?

Data Tables

## Why do we need it?

In order to increase exposure of the canary components, canary component documentation is required on the guidance site in addition to Storybook..

Move https://mi6.github.io/ic-ui-kit/branches/canary/main/web-components/?path=/docs/web-components-data-table--docs to guidance site

## Related open issues

N/A

**Comment by GCHQ-Developer-741** [comment]
Closing as task is moving into #929
