### ISSUE TITLE
Change to ic-side-navigation 'Layout example'

### ISSUE THREAD

**Issue by gd2910** [mi6/ic-design-system#878]
## Summary of the bug

The IcSideNavigation layout example needs a style change on the <main> tag.
Current:
`<main style={{height: '100vh'}}>`
Change to:
`<main style={{minHeight: '100vh'}}>`

Base code, web-component and react code snippets will need to be updated.

## 🪜 How to reproduce

1. Go to page: ['layout example'](https://design.sis.gov.uk/side-navigation-layout)
2. Shrink the window and scroll down
3. See that the IcTypography is overlapping the footer

## 🧐 Expected behaviour

Typography should not overlap footer

**Comment by MI6-255** [comment]
Instead of fixing it, change this to remove the example and instead redirect to patterns
