### ISSUE TITLE
Centre VS center

### ISSUE THREAD

**Issue by gd2910** [mi6/ic-design-system#949]
## Summary of the bug

Component props use the Americanised version and the guidance uses the English spelling, discuss wether to change the spelling throughout the guidance or leave as-is.

There is some dissonance when viewing code examples, such as the title being `Centre aligned` and the prop used `aligned: center`

**Comment by srt544** [comment]
After insight from others it seems that it would make sense that prop values are left American to align with the code and the guidance in British. It wouldn't cause much confusion and an external user may even appreciate the British spelling in the guidance.
