### ISSUE TITLE
Add icon only variant to back to top in Figma

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-design-system#960]
## Summary

Work has been done to add a new `icon` only `variant` of the back to top component. This was completed in the developed components under https://github.com/mi6/ic-ui-kit/issues/1849

An update to Figma is required to ensure equivalent functionality is available

The terminology used in the build component is `variant` with a value of `icon` or `default`. If this doesn't seem appropriate, we could raise a ticket to revise this 

## 📝 Acceptance Criteria

If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.

_Given_ a back to top component exists
_When_  using the component
_Then_ an option to use an icon only variant, without a label, exists

## Guidance
will be covered by #958

**Comment by GCHQ-Developer-094** [comment]
Completed, merged, and published as part of v2.2
