### ISSUE TITLE
'Canary' status tag in Component Gallery Cards

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-design-system#981]
## Summary

The status tag used on the Component Gallery cards are causing a bug when hovering. The hover state is too close and looks odd when touching the status tag. (See attached)

## 💬 Description

Either just remove the status tags, as having the status tags in the component gallery look slightly strange and odd. We don't have the 'beta' status tags on the component gallery. 

Or extra styling is needed on the cards, so that there is space in between the hover state and the tag. (See attached)

## 💰 Use value

To make the site look better and have consistency. 

## Additional info

<img width="386" alt="Screenshot 2024-05-21 at 09 32 10" src="https://github.com/mi6/ic-design-system/assets/111882114/4270ee07-6f27-4f54-9e41-c1fe9c1259d8">

**Comment by GCHQDeveloper823** [comment]
Changing the colour of the status tags from yellow to grey
